# Generated by Django 4.1.6 on 2023-02-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
            },
        ),
        migrations.CreateModel(
            name='ExamTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskText', models.TextField(verbose_name='Задание')),
                ('idExam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exam')),
            ],
            options={
                'verbose_name': 'Задание экзамена',
                'verbose_name_plural': 'Задания экзамена',
            },
        ),
        migrations.CreateModel(
            name='PracticalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskText', models.TextField(verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Практическое задание',
                'verbose_name_plural': 'Практические задания',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('classNum', models.IntegerField(verbose_name='Класс')),
                ('presName', models.CharField(max_length=30, verbose_name='Путь к презентации')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя Фамилия')),
                ('login', models.CharField(max_length=150, verbose_name='Логин')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
                ('classNum', models.IntegerField(verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='StudAnsPract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.IntegerField(verbose_name='Ответ')),
                ('idStud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('idTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.practicaltask')),
            ],
            options={
                'verbose_name': 'Ответ ученика на практическое задание',
                'verbose_name_plural': 'Ответы ученика на практические задания',
            },
        ),
        migrations.CreateModel(
            name='StudAnsExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.IntegerField(verbose_name='Ответ')),
                ('idStud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('idTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.examtask')),
            ],
            options={
                'verbose_name': 'Ответ студента на экзаменационное задание',
                'verbose_name_plural': 'Ответы студента на экзаменационные задания',
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSubj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
            options={
                'verbose_name': 'Практика',
                'verbose_name_plural': 'Практики',
            },
        ),
        migrations.AddField(
            model_name='practicaltask',
            name='idPractice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.practice'),
        ),
        migrations.AddField(
            model_name='exam',
            name='idSubj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
        migrations.CreateModel(
            name='AnsPract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans1', models.IntegerField(verbose_name='Ответ 1')),
                ('ans2', models.IntegerField(verbose_name='Ответ 2')),
                ('ans3', models.IntegerField(verbose_name='Ответ 3')),
                ('ans4', models.IntegerField(verbose_name='Ответ 4')),
                ('rightAns', models.IntegerField(verbose_name='Правильный ответ')),
                ('idTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.practicaltask')),
            ],
            options={
                'verbose_name': 'Ответ на практическое задание',
                'verbose_name_plural': 'Ответы на практические задания',
            },
        ),
        migrations.CreateModel(
            name='AnsExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans1', models.IntegerField(verbose_name='Ответ 1')),
                ('ans2', models.IntegerField(verbose_name='Ответ 2')),
                ('ans3', models.IntegerField(verbose_name='Ответ 3')),
                ('ans4', models.IntegerField(verbose_name='Ответ 4')),
                ('rightAns', models.IntegerField(verbose_name='Правильный ответ')),
                ('idTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.examtask')),
            ],
            options={
                'verbose_name': 'Ответ на экзаменационное задание',
                'verbose_name_plural': 'Ответы на экзаменационные задания',
            },
        ),
    ]
